name: Refresh GitHub Stats

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:        # Manual trigger

jobs:
  refresh-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh stats cache
        run: |
          # This forces the stats to regenerate
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=${{ github.repository_owner }}&layout=compact&theme=radical&cache_bust=${{ github.run_id }}" > /dev/null
          curl -s "https://github-readme-stats.vercel.app/api?username=${{ github.repository_owner }}&show_icons=true&theme=radical&cache_bust=${{ github.run_id }}" > /dev/null
